version: "3.7"

networks:
  big_net:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16

services:
  web:
    image: alpine
    command: ["tail", "-f", "/dev/null"]
    networks:
      - big_net
